apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: test-delete2
  namespace: karim-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kubevirt
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
