apiVersion: v1
kind: Template
metadata:
  name: dummy
  annotations:
    description: "Dummy template"
    tags: "ocp,template,dummy"
    iconClass: icon-jruby
  labels:
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: http-${NAME}
  spec:
    ports:
    - name: http
      port: 80
    selector:
      kubevirt.io/domain: ${NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: http-${NAME}
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: http-${NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- name: NAME
  description: Name for my dumb service
