---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: windows
spec:
  storageClassName: glusterfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
Version: v1
kind: Pod
metadata:
  name: windows-importer
spec:
  restartPolicy: OnFailure
  containers:
  - name: importer
    image: kubevirtci/disk-importer
    env:
      - name: CURL_OPTS
        value: "-L"
      - name: INSTALL_TO
        value: /storage/disk.img
      - name: URL
        value: http://10.19.139.34/win-test.raw
    volumeMounts:
    - name: storage
      mountPath: /storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: windows
