apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: kubevirt
  namespace: kube-system
spec:
  clusterServiceClassExternalName: dh-kubevirt-apb
  clusterServicePlanExternalName: gluster
  parameters:
    admin_user: developer
    admin_password: developer
    storage_role: storage-glusterfs
    tag: v0.4.1-alpha.1
