apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: windows-pvc-vm2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 33Gi
  storageClassName: glusterfs-storage
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 33Gi
