apiVersion: v1
kind: Template
metadata:
  name: kubevirt-windows2016-vm-template
  annotations:
    description: "OCP KubeVirt Microsoft Windows Server 2016 VM template"
    tags: "kubevirt,ocp,template,windows"
  labels:
    kubevirt.io/os: win2k16
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt-ovm: ovm-${NAME}
  spec:
    running: true
    selector:
      matchLabels:
        kubevirt-ovm: ovm-${NAME}
    template:
      metadata:
        labels:
          kubevirt-ovm: ovm-${NAME}
      spec:
        domain:
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              vapic: {}
              spinlocks:
                spinlocks: 8191
          clock:
            utc: {}
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
              hyperv: {}
          cpu:
            cores: 4
          machine:
            type: q35
          resources:
            requests:
              memory: ${{MEMORY}}
          devices:
            disks:
              - name: disk0
                volumeName: disk0-pvc
        nodeSelector:
          region: master
        volumes:
          - name: disk0-pvc
            persistentVolumeClaim:
              claimName: ${PVC_NAME}
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: 8192Mi
- name: CPU_CORES
  description: Amount of cores
  value: "4"
- name: PVC_NAME
  description: Amount of cores
  value: "windows-pvc-vm1"
