---
#- hosts: nodes
#  remote_user: root
#  tasks:
#  - name: ensure selinux is disabled
#    selinux:
#      policy: targeted
#      state: permissive

- hosts: master01
  remote_user: centos
  become: true
  vars:
    user: developer
    password: developer
    version: v0.4.0-alpha.1
    plan: cns
  tasks:
  - name: install virtctl
    get_url:
     url: "https://github.com/kubevirt/kubevirt/releases/download/{{ version }}/virtctl-{{ version }}-linux-amd64"
     dest: /usr/bin/virtctl
     mode: 0700
  - name: install console utilities
    yum:
      name: "{{ item }}"
    with_items:
      - xorg-x11-xauth
      - virt-viewer
  - name: render kubevirt service instance
    template:
     src: si.yml.j2
     dest: /tmp/si.yml
  - name: install kubevirt service instance
    command: /usr/local/bin/oc create -f /tmp/si.yml
