---

- name: Configure developer user as cluster admin
  shell: |
    oc login -u system:admin
    oc adm policy add-cluster-role-to-user cluster-admin "{{ user }}"

- include_tasks: check_vm.yml
  
- name: Delete vms
  shell: "oc process kubevirt-{{ type }} -p Name={{ name }} | oc delete -f - -n {{ namespace }}"
  ignore_errors: yes

- name: Delete vm templates
  command: "oc delete template kubevirt-{{ item }} -n openshift"
  ignore_errors: yes
  with_items:
  - linux
  - windows
  - import

- name: Delete import disk service instances
  shell: "oc delete serviceinstance {{ name }} -n {{ namespace }}"
  ignore_errors: yes

#- name: Delete pvcs
#  command: "oc delete pvc {{ item.name }} -n {{ namespace }}"
#  with_items: {{ vms }}
#  ignore_errors: yes

- name: Delete kubevirt service instances
  shell: "oc get serviceinstance -l task=kubevirt -n kube-system -o name | xargs -r oc delete -n kube-system"
  ignore_errors: yes

#-  meta: end_play
