---

- name: Configure developer user as cluster admin
  shell: |
    oc login -u system:admin
    oc adm policy add-cluster-role-to-user cluster-admin "{{ user }}"

- name: Delete vms
  shell: "oc process kubevirt-{{ item.type }} -p Name={{ item.name }} | oc delete -f - -n {{ item.namespace }}"
  ignore_errors: yes
  with_items: "{{ vms | selectattr('run',true) }}"
  when: vms is defined and vms

- name: Delete vm templates
  command: "oc delete template kubevirt-{{ item }} -n openshift"
  ignore_errors: yes
  with_items:
  - linux
  - windows

- name: Delete import disk service instances
  shell: "oc delete serviceinstance {{ item.name }} -n {{ item.namespace }}"
  ignore_errors: yes
  with_items: "{{ vms }}"
  when: vms is defined and vms and plan == 'gluster'

#- name: Delete pvcs
#  command: "oc delete pvc {{ item.name }} -n {{ namespace }}"
#  with_items: {{ vms }}
#  ignore_errors: yes

- name: Delete kubevirt service instances
  shell: "oc get serviceinstance -l task=kubevirt -n kube-system -o name | xargs oc delete -n kube-system"
  ignore_errors: yes

#-  meta: end_play
