---

- name: Configure developer user as cluster admin
  shell: |
    oc login -u system:admin
    oc adm policy add-cluster-role-to-user cluster-admin "{{ user }}"

- name: Install apb tool
  yum:
   name: apb
  state: present

- name: install virtctl
  get_url:
   url: "https://github.com/kubevirt/kubevirt/releases/download/v{{ version }}/virtctl-v{{ version }}-linux-amd64"
   dest: /usr/bin/virtctl
   mode: 0700

- name: Set Cloudinit Data
  set_fact:
   cloudinit: "{{ lookup('template', 'cloudinit.yml.j2') }}"
  when: public_key is defined

- name: Render vm templates
  template:
   src: "{{ item }}-template.yml.j2"
   dest: "/tmp/vmtemplate-{{item}}.yml"
  with_items:
   - linux
   - windows

- name: Deploy vm template
  command: "oc apply -f /tmp/vmtemplate-{{ item }}.yml -n {{ namespace }}"
  with_items:
   - linux
   - windows

- include_tasks: sync.yml
  when: sync

- include_tasks: kubevirt.yml
  when: kubevirt

- include_tasks: import.yml
  when: import
