---

- name: Configure developer user as cluster admin
  shell: |
    user_name="{{ user }}"
    kubeconfig="/etc/origin/master/admin.kubeconfig"
    oc login -u system:admin --config=$kubeconfig
    oc get user "$user_name" --config=$kubeconfig || oc create user "$user_name" --config=$kubeconfig
    oc adm policy add-cluster-role-to-user cluster-admin "$user_name" --config=$kubeconfig

- name: Render kubevirt service instance
  template:
   src: "kubevirt.yml.j2"
   dest: /tmp/kubevirt.yml

- name: Deploy kubevirt service instance
  command: /usr/local/bin/oc create -f /tmp/kubevirt.yml 

- name: Render import disk service instance
  template:
   src: "import-disk-apb.yml.j2"
   dest: /tmp/import-disk-apb.yml

- name: Deploy import disk service instance
  command: /usr/local/bin/oc create -f /tmp/import-disk-apb.yml

- name: Render sample vm template
  template:
   src: "runonce.j2"
   dest: /tmp/runonce.yml

- name: Deploy sample vm
  command: oc process -f /tmp/runonce.yml -p Name={{ vm_name }} | oc create -f - -n

#- name: Create default VM templates in OpenShift Namespace
#  shell: "oc apply -f /tmp/kubevirt-{{ version }}/cluster/{{ item }}.yaml -n openshift"
#  with_items:
#    - "{{ default_vm_templates }}"
#  when: cluster == "openshift"
